server:
  port: 8089

spring:
###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
#      settings:
#        trace: false
#        web-allow-others: false

  datasource:
    url: jdbc:h2:mem:reservedb;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace


